In [71]:
%matplotlib inline

## Documentation:

##  100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described `here <https://pytorch.org/docs/torch>`_.


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [72]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



# construct a matrix

1. Construct a 5x3 matrix, uninitialized:



In [73]:
x = torch.empty((2,2),dtype=torch.float32)
torch.empty_like(x)
print(x)

tensor([[0., 0.],
        [0., 0.]])


2. Construct a randomly initialized matrix:



In [74]:
x = torch.rand(5, 3,dtype = torch.float16)
print(x)

tensor([[0.9258, 0.8672, 0.4238],
        [0.6235, 0.9795, 0.7212],
        [0.6226, 0.9844, 0.9565],
        [0.4482, 0.5312, 0.2866],
        [0.8867, 0.7715, 0.1494]], dtype=torch.float16)


Pytorch has different data types:
https://pytorch.org/docs/stable/tensors.html

3. Construct a matrix filled zeros and of dtype long (equivalent as torch.int64):

In [75]:
x = torch.rand(3, 3, dtype=torch.float64)+100
print(x,type(x))

tensor([[100.9830, 100.5798, 100.2602],
        [100.2573, 100.2624, 100.6780],
        [100.7552, 100.2579, 100.5552]], dtype=torch.float64) <class 'torch.Tensor'>


4 .Construct a tensor directly from data:
similiar as np.array


In [76]:
x = torch.tensor([5.5, 3.3],dtype = torch.short)  
print(x)

tensor([5, 3], dtype=torch.int16)


<ipython-input-76-efdf14ef3d06>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  x = torch.tensor([5.5, 3.3],dtype = torch.short)


5. or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [77]:
x = x.new_ones(5, 3)      # new_* methods allow us to define new sizes of the tensor
print(x)                 # essentially, new_ones allows you to quickly create a new torch.Tensor on the same device and data type as a previously existing tensor (with ones), whereas ones() serves the purpose of creating a torch.Tensor from scratch (filled with ones)
print(type(x.data))    # inherit the data type from previous x.

x = x.new_zeros(5,3,dtype = torch.float32)     # can also define new data type
print(x)
print(type(x.data))

x = torch.ones_like(x)
print(x)

x = torch.randn_like(x)    # Returns a tensor with the same size as input that is filled with random numbers from a normal distribution with mean 0 and variance 1.
print(x)                                      # result has the same size

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.8217, -0.4795,  0.3934],
        [-0.6245,  1.4906,  0.9114],
        [-0.3431, -0.1834,  0.6050],
        [-0.7738, -0.1787,  1.9777],
        [ 1.3456, -1.4953, -0.0944]])


# Get tensor's size and data:

In [78]:
a = x.size()
print(a,a[0])
b = x.data
print(b,b[0],b[0,1])

torch.Size([5, 3]) 5
tensor([[ 0.8217, -0.4795,  0.3934],
        [-0.6245,  1.4906,  0.9114],
        [-0.3431, -0.1834,  0.6050],
        [-0.7738, -0.1787,  1.9777],
        [ 1.3456, -1.4953, -0.0944]]) tensor([ 0.8217, -0.4795,  0.3934]) tensor(-0.4795)


In [79]:
# to get the real value of one element in the pytorch
print(b.numpy()[0,1])

-0.47952563


In [80]:
# for single element tensor, can use .item for value
x = torch.randn(1)
print(x)
print(x.item())
x = torch.tensor([5.6],dtype = torch.int)
print(x.item())
print(torch.is_tensor(x))

tensor([-0.5946])
-0.5945529937744141
5
True


<ipython-input-80-f23da3280aeb>:5: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  x = torch.tensor([5.6],dtype = torch.int)


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

# Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [81]:
x = torch.ones((2,4),dtype = torch.int)
y = torch.tensor([[1,1,1,1],[2,2,2,2]],dtype = torch.int)
print(y.size())
print(x + y)

torch.Size([2, 4])
tensor([[2, 2, 2, 2],
        [3, 3, 3, 3]], dtype=torch.int32)


Addition: syntax 2



In [83]:
print(torch.add(x, y))
print(torch.subtract(x,y))
print(torch.multiply(x,y))
print(x.add(y))

tensor([[2, 2, 2, 2],
        [3, 3, 3, 3]], dtype=torch.int32)
tensor([[ 0,  0,  0,  0],
        [-1, -1, -1, -1]], dtype=torch.int32)
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]], dtype=torch.int32)
tensor([[2, 2, 2, 2],
        [3, 3, 3, 3]], dtype=torch.int32)


In [88]:
x = torch.tensor([[1,3],[2,2]])
y = x + 2
zz = torch.mm(y,x)  # matrix multiplication
zzz = torch.matmul(y,x)
print(zz)
print(zzz)

tensor([[13, 19],
        [12, 20]])
tensor([[13, 19],
        [12, 20]])


In [ ]:
x = torch.tensor([[1,3],[2,2]], requires_grad=True, dtype = torch.float32)
y = (x + 2) 
z = torch.tensor([[1,1],[1,1]],dtype = torch.float32)
zz = torch.mm(y,z)  # matrix multiplication
zzz = torch.matmul(y,z)
print(y)
print(zz)
print(zzz)

Addition: providing an output tensor as argument



In [ ]:
# two ways have equal effect
result = torch.empty(5, 3)
torch.add(x, y, out=result) 
print(result)
result = x + y 
print(result)

# concatenate

In [86]:
t1 = torch.cat([x,y], dim=0)
print(t1)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [2, 2, 2, 2]], dtype=torch.int32)


# Change a tensor: don't forget the "_"

In [51]:
# adds x to y
x = torch.tensor([1,2],dtype = torch.int32)
y = torch.tensor([10,20],dtype = torch.int32)
y.add_(x)
x.copy_(y)
print(x)
print(y)

tensor([11, 22], dtype=torch.int32)
tensor([11, 22], dtype=torch.int32)


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [54]:
print(y.t_(),y.size(),y.t_(),y.size())          # transpose
x.copy_(torch.tensor([3.7,3.7]))                      # copy
print(x)

tensor([11, 22], dtype=torch.int32) torch.Size([2]) tensor([11, 22], dtype=torch.int32) torch.Size([2])
tensor([3, 3], dtype=torch.int32)


# Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [61]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
zz = x.view(-1,4)
print(x.size(), y.size(), z.size(),zz.size(),z.t_().size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([4, 4]) torch.Size([8, 2])


NumPy Bridge
------------

1. Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

simply use .numpy()

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [66]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [67]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


See how the numpy array changed in value.

by changing a, b will also be changed.


In [68]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


2. Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

simply use torch.from_numpy()




In [69]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) 
np.add(a, 1, out=a)   # however, if use a = a+1, then b won't change
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [70]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [72]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!